data <- read.csv("household_power_consumption.txt",sep=";",na.strings="?")
data$Date <- as.Date(data$Date,"%d/%m/%Y")

Date1 <- as.Date("01-02-2007","%d-%m-%Y")
Date2 <- as.Date("02-02-2007","%d-%m-%Y")

main_data <- subset(data,Date >= Date1 & Date <= Date2)
main_data$days <- weekdays(main_data$Date)
possible_days <- factor(main_data[,"days"])
thu <- length(possible_days[possible_days == "Thursday"])
fri <-  length(possible_days[possible_days == "Friday"])

png('plot3.png')
plot(main_data$Sub_metering_1, type='l', col="black",xaxt="n",ylab="Energy sub metering",xlab="")
lines(main_data$Sub_metering_2,col="red",xaxt="n")
lines(main_data$Sub_metering_3, type='l', col="blue",xaxt="n")
plot_colors <- c("black", "red", "blue")
legend(x = "topright",legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),bty = "o",lwd = 2, cex = 1.2, col=plot_colors,lty = c(1, 1, 1), pch = c(NA,NA,NA))
axis(1, at=c(1, thu,thu+fri), labels=c("Thu", "Fri","Sat"))
dev.off()
